version: '3.0'
# volumes:
#   mongo-data-stikinote:
services:
  # mongo:
  #   image: mongo:4.0
  #   volumes:
  #     - mongo-data-stikinote:/data/db
  #     - .docker/backup:/backup
  #   # env_file: ./mongod.env
  #   ports:
  #     - 27017:27017

  # reds:
  #   image: redis:5-alpine
  #   volumes:
  #     - .docker/redis-data:/data
  #   restart: unless-stopped

  pizza:
    image: nomorechokedboy/web-project:pizza-api-prod
    volumes:
      - ./:/app
      - /app/node_modules/
    environment:
      - PORT=$PORT
      - MONGODB=$MONGO_HOST://$MONGO_USER:$MONGO_PASSWORD@stikinote.bzd5w.mongodb.net/$PIZZA_DB?retryWrites=true&w=majority
      - MORGAN=$MORGAN
      - NODE_ENV=production
      - PIZZA_DB=$PIZZA_DB
      - refreshTokenKey=$refreshTokenKey
      - SECRET_KEY=$SECRET_KEY
    ports:
      - '${PORT}:${PORT}'
    # restart: unless-stopped
    # depends_on:
    #   - mongo
    # - redis
  # adminmongo:
  #   image: "mrvautin/adminmongo"
  #   ports:
  #     - 1235:1234
  #   environment:
  #     - HOST=0.0.0.0
#     networks:
#       - italian-gang_default

# networks:
#   italian-gang_default:
#     driver: bridge
#     ipam:
#       config:
#         - subnet: 172.24.0.0/16
#           gateway: 172.24.0.1
