name: CI workflows
on:
    push:
        branches-ignore:
            - master
        paths:
            - 'src/**'
            - 'index.ts'
            - 'src/index.ts'

jobs:
    build-test:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.x]

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
            - name: ci, build and test
              run: |
                  yarn 
                  yarn lint
                  yarn build
                  # yarn test
